### ISSUE TITLE
Add support for natural=spring drinking water

### ISSUE THREAD

**Issue by incognico** [ToastHawaii/priceless-map#23]
The drinking water overlay does not show (all?) natural springs.

`natural=spring` (and maybe some others) can include `drinking_water=yes` as as subkeyvalue, it seems the map shows only `amenity=drinking_water` (which automatically implicates `drinking_water=yes`) but misses natural springs who are subtagged.

https://wiki.openstreetmap.org/wiki/Key:drinking_water#Applies_to_.28among_other_things.29

Edit: Maybe also consider a separate overlay for natural springs, as the water of those is mostly drinkable anyways (and very few have the `drinking_water=yes` tag).

**Comment by ToastHawaii** [comment]
`drinking_water=yes` should be displayed, do you have an example where it doesn't work? 

![image](https://user-images.githubusercontent.com/1504145/128520189-1f0ef778-39df-4c50-862f-6fbaf11ed30c.png)

I don't want to show `natural=spring` as drinking water unless it is tagged with drinking_water. Because the health of the users is important to me.

But I want to add `natural=spring` in the category "Nature", so you can activate both (at the same time) to see what you want.
What do you think about that?

**Comment by incognico** [comment]
> But I want to add `natural=spring` in the category "Nature", so you can activate both (at the same time) to see what you want.
> What do you think about that?

That would be the best solution I think.

**Comment by ToastHawaii** [comment]
Done https://priceless.zottelig.ch/?offers=natural%2Fspring

**Comment by incognico** [comment]
Thanks for that! I noticed another one not showing up under drinking_water tho: https://www.openstreetmap.org/node/3027815367

**Comment by ToastHawaii** [comment]
> Thanks for that! I noticed another one not showing up under drinking_water tho: https://www.openstreetmap.org/node/3027815367

Yes, that is correct. I do not show drinking_water:legal=no as a drinking water.

 https://wiki.openstreetmap.org/wiki/Key:drinking_water:legal
