### ISSUE TITLE
Add a "share" button

### ISSUE THREAD

**Issue by Binnette** [ToastHawaii/priceless-map#6]
Hi again @ToastHawaii & ty for your map, i'm using it a lot nowadays :wink:

I was thinking about a new feature for your map : a "share" button.

Now if I wnat to share a map, i need to copy a very long link like (decoded) : https://priceless.zottelig.ch/#offers=culture/archaeological-site,culture/artwork,culture/castle,culture/fountain,culture/history,culture/memorial,culture/mill,culture/monument,culture/ruins,culture/tourist-attraction,natural/viewpoint,natural/waterfall,natural/pond,goods/clothes-take,goods/clothes-repair,education/book-exchange,education/internet,community/hackerspace,community/coworking,community/contribute,community/community-garden,community/community-centre,community/assisted-repair,community/assistance&location=44.905738,4.422963

What can be cool is to shorten & encode all parameter to have a short link.

For example, you should consider encode "offers" as binary:

- culture/archaeological-site (enabled) = 0000 0001
- culture/archaeological-site (disabled) = 0000 0000
- culture/artwork (enabled) = 0000 0010
- culture/artwork (disabled) = 0000 0000
- [...]
- community/assisted-repair (enabled) 0100 0000
- community/assisted-repair (disabled) 0000 0000
- community/assistance (enabled) = 1000 0000
- community/assistance (enabled) = 0000 0000

For example, for artwork & assistance, i will get this binary number = 1000 0010
And encoded to hexadecimal, you will get "82" or in decimal "130".

So the short link will be :

https://priceless.zottelig.ch/#offers=82&location=44.905738,4.422963

It is a lot more shorter 😉 

It is just an idea of what you can do if you want to make the "share button" feature :)

Of course, we can discuss about it and if you want i can implement it and make a pull request.

Have a nice day. And again thank for your map !

PS : i really like to use your map to view pictures places with pictures from Commons. Each time, the photo is missing, i tried to add a commons picture in OSM node/way.

**Comment by ToastHawaii** [comment]
Hello @Binnette 

Thanks for your message, your idea and your concept. It makes me happy to hear that you like and use my priceless map. To get appreciation and to be able to contribute something are important to me.

Based on your concept I implement a share button of the current view. (See bottom right in the corner. 😄 )

It was harder as I expected 😉 Because there were many filters. I needed to use bignumber and base 36 instead of decimal or hexadecimal to get a short string.

Your link look now like this: https://priceless.zottelig.ch/#o=4jv8i74dcuyy32rwwjvxr&b=44.9040,4.4205,44.9076,4.4257

I also add it to the other two projects https://book-exchange.zottelig.ch/, https://sustainable.zottelig.ch/ 

I also want to update/improve the item share button in the popup in the next days.

Best regards

ToastHawaii

**Comment by Binnette** [comment]
🚀 👍 You are GREAT ! Thanks a lot for this feature ! 😉 

I do NOT know yet your "sustainable" project : https://sustainable.zottelig.ch/

I allready have an idea for this map ^^

Thanks a lot for your work!
